### ISSUE TITLE
Format for InSAR data

### ISSUE THREAD

**Issue by bjmarfito** [Xiaohua-Eric-Xu/Geodetic_Inversion_Package_with_Matlab#1]
Hi @Xiaohua-Eric-Xu, I checked the example dataset for InSAR data for this code. However, I can't understand the meaning of the third to the last column. I assumed that the first two columns are longitude and latitude. Regarding this, can you please provide me the information for each columns?

**Comment by Xiaohua-Eric-Xu** [comment]
Oh, The format should be longitude, latitude, elevation, look_e, look_n, look_u, defo_los, err.

**Comment by bjmarfito** [comment]
Thank you for your reply, @Xiaohua-Eric-Xu. 

Then, what is the unit of elevation, defo_los and error? meter or cm?
For the elevation data, can I just pad them with zeros or is it needed in the inversion?
Also for the elevation data, should they be in ellipsoidal or geoidal height?

**Comment by bjmarfito** [comment]
Hi @Xiaohua-Eric-Xu, I tried the Maule earthquake example but the coordinates of lon and lat data plots to the ocean near Antarctica in the plotting figure for InSAR data. I interchanged the lon and lat coordinates and the location is now okay.

**Comment by bjmarfito** [comment]
Figured it out. The x0 in the main_inv was commented out which is causing the switch in lon and lat.

**Comment by bjmarfito** [comment]
I'm closing this issue. Figured it out. Thank you @Xiaohua-Eric-Xu!

**Comment by Xiaohua-Eric-Xu** [comment]
> Thank you for your reply, @Xiaohua-Eric-Xu.
> 
> Then, what is the unit of elevation, defo_los and error? meter or cm? For the elevation data, can I just pad them with zeros or is it needed in the inversion? Also for the elevation data, should they be in ellipsoidal or geoidal height?

I am sorry for the late response. I was out on a field trip for a week with lots of students. 

The unit of the elevation is in meters. You could just pad them with zeros as for elastic half space, the effect is small (equivalent to making the source a bit deeper). The elevation should be above ellipsoidal I believe. 

Let me know if you have any other questions. I understand that some of the parameter setups could be very confusing.

**Comment by bjmarfito** [comment]
No worries.
