### ISSUE TITLE
Smoothing factor in test_inv.m is zero

### ISSUE THREAD

**Issue by bjmarfito** [Xiaohua-Eric-Xu/Geodetic_Inversion_Package_with_Matlab#2]
Hi @Xiaohua-Eric-Xu, I noticed that the smoothing factor (SF) in the Green's function to invert data generated from "checkerboard test" in test_inv.m is zero. Is this correct since there will be no smoothing applied during the inversion or should I changed it to reflect the smoothing weight I used during inversion?

**Comment by Xiaohua-Eric-Xu** [comment]
I think you may need to change the smoothing weigh you used in the inversion as that'll be more reflective of the model you produced. After all what the checker board test only provide info on when it definitely fails, not actually the real resolution.

**Comment by bjmarfito** [comment]
Please correct me if I'm wrong. It means that during checkerboard test smoothing is not applied.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Bryan, it should be applied as regularization will affect the solution. So when testing the resolving capabilities with checker board, smoothness is needed.

**Comment by bjmarfito** [comment]
Got it. Thank you!

Closing this issue.
